services:
  - type: web
    name: rkb
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn music.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: music.settings
      - key: PYTHON_VERSION
        value: 3.10
