services:
  - type: web
    name: rkb
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn music.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: music.settings
      - key: PYTHON_VERSION
        value: 3.11
