# Generated by Django 5.2.4 on 2025-07-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('stage_name', models.CharField(blank=True, help_text='Also known as', max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='artist_profiles/')),
                ('age', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('biography', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('facebook_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
