# Generated by Django 5.2.4 on 2025-07-12 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover_art', models.ImageField(blank=True, null=True, upload_to='song_covers/')),
                ('audio_file', models.FileField(upload_to='songs/')),
                ('genre', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('download_link', models.URLField(blank=True)),
                ('streaming_link', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rkb.artist')),
            ],
        ),
    ]
