# Generated by Django 5.2.4 on 2025-07-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkb', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('description', models.TextField()),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags (e.g., reviews, afrobeats, trending)', max_length=200)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
