# Generated by Django 5.2.4 on 2025-07-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkb', '0005_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sponsor_name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('video', models.FileField(blank=True, null=True, upload_to='ads/videos/')),
                ('link', models.URLField(blank=True, help_text='Where the ad redirects to')),
                ('caption', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
