# Generated by Django 5.2.4 on 2025-07-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkb', '0008_alter_song_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submittedsong',
            old_name='is_approved',
            new_name='is_reviewed',
        ),
        migrations.RenameField(
            model_name='submittedsong',
            old_name='description',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='submittedsong',
            name='genre',
        ),
        migrations.AlterField(
            model_name='submittedsong',
            name='artist_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
