# Generated by Django 5.2.4 on 2025-07-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkb', '0009_rename_is_approved_submittedsong_is_reviewed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main title in the hero section', max_length=255)),
                ('subtitle', models.CharField(help_text='Subtitle or description', max_length=255)),
                ('image', models.ImageField(upload_to='hero_banners/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
