# Generated by Django 5.2.4 on 2025-07-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkb', '0012_video_album_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
