# Generated by Django 5.2.4 on 2025-07-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkb', '0013_song_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='cover_image',
            new_name='cover_art',
        ),
        migrations.RemoveField(
            model_name='album',
            name='release_date',
        ),
        migrations.AddField(
            model_name='album',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
